export const hero = [
  {
    id: 1,
    cover: "../images/hero/hero1.jpg",
    title: "Google To Boost Android Security In Few Days",
    authorName: "Ann Jones",
    authorImg: "../images/author.jpg",
    time: "5 Jun - 2024",
    desc: [
      {
        para1: "You audience. Least, the recently his repeat the this avarice for the have and was on would before the concise bedding were hall politely name be regretting have of even five of it the his are there again. Word seven designer far lady problem will have work with you to fully understand your business to achieve.",
      },
      {
        para2: "We work with clients big and small across a range of sectors and we utilize all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you.",
      },
      {
        para3: "We have a number of different teams within our agency that specialise in different areas of business so you can be sure that you won’t receive a generic service and although we can’t boast years and years of service we can ensure you that is a good thing in this industry.",
      },
    ],
    details: [
      {
        title: "Starting a new company is easy",
      },
      { para1: "Our teams are up to date with the latest technologies, media trends and are keen to prove themselves in this industry and that’s what you want from an advertising agency, not someone who is relying on the same way of doing things that worked 10 years, 5 years or even a year ago." },
      {
        quote: "Scarfs, still not this no with explains it me and option on the any options roasted when I and state can that an don't subjective of has his take on and in from royal everything took raising our have behind success you the mechanic.",
      },
      {
        para2: "And, higher by agency; In from their in and we spirit, through merely and doctor's small him sounded a all now, with that put gift white highly geared that was left back as of or logged important. A over have the large try understanding the believe. Perfected been viewer. Shreds early willingly safely what passion the.",
      },
      {
        para3: "In an ideal world this website wouldn’t exist, a client would acknowledge the importance of having web copy before the design starts. Needless to say it’s very important, content is king and people are beginning to understand that. However, back over in reality some project schedules and budgets don’t allow for web copy to be written before the design phase, this is sad but true.",
      },
    ],
  },
  {
    id: 2,
    cover: "../images/hero/hero2.jpg",
    title: "Indian cricket fans unite to celebrate the homecoming of the T20 world cup after 17 years  ",
    authorName: "arun",
    authorImg: "../images/author.jpg",
    time: "5 Jul - 2024",
    desc: [
      {
        para1: "You audience. Least, the recently his repeat the this avarice for the have and was on would before the concise bedding were hall politely name be regretting have of even five of it the his are there again. Word seven designer far lady problem will have work with you to fully understand your business to achieve.",
      },
      {
        para2: "We work with clients big and small across a range of sectors and we utilize all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you.",
      },
      {
        para3: "We have a number of different teams within our agency that specialise in different areas of business so you can be sure that you won’t receive a generic service and although we can’t boast years and years of service we can ensure you that is a good thing in this industry.",
      },
    ],
    details: [
      {
        title: "Starting a new company is easy",
      },
      { para1: "Our teams are up to date with the latest technologies, media trends and are keen to prove themselves in this industry and that’s what you want from an advertising agency, not someone who is relying on the same way of doing things that worked 10 years, 5 years or even a year ago." },
      {
        quote: "Scarfs, still not this no with explains it me and option on the any options roasted when I and state can that an don't subjective of has his take on and in from royal everything took raising our have behind success you the mechanic.",
      },
      {
        para2: "And, higher by agency; In from their in and we spirit, through merely and doctor's small him sounded a all now, with that put gift white highly geared that was left back as of or logged important. A over have the large try understanding the believe. Perfected been viewer. Shreds early willingly safely what passion the.",
      },
      {
        para3: "In an ideal world this website wouldn’t exist, a client would acknowledge the importance of having web copy before the design starts. Needless to say it’s very important, content is king and people are beginning to understand that. However, back over in reality some project schedules and budgets don’t allow for web copy to be written before the design phase, this is sad but true.",
      },
    ],
  },
  {
    id: 3,
    cover: "../images/hero/hero3.jpg",
    title: "Explore the latest electric car options of 2024 ",
    authorName: "rina",
    authorImg: "../images/author.jpg",
    time: "22 Mar - 2022",
    desc: [
      {
        para1: "You audience. Least, the recently his repeat the this avarice for the have and was on would before the concise bedding were hall politely name be regretting have of even five of it the his are there again. Word seven designer far lady problem will have work with you to fully understand your business to achieve.",
      },
      {
        para2: "We work with clients big and small across a range of sectors and we utilize all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you.",
      },
      {
        para3: "We have a number of different teams within our agency that specialise in different areas of business so you can be sure that you won’t receive a generic service and although we can’t boast years and years of service we can ensure you that is a good thing in this industry.",
      },
    ],
    details: [
      {
        title: "Starting a new company is easy",
      },
      { para1: "Our teams are up to date with the latest technologies, media trends and are keen to prove themselves in this industry and that’s what you want from an advertising agency, not someone who is relying on the same way of doing things that worked 10 years, 5 years or even a year ago." },
      {
        quote: "Scarfs, still not this no with explains it me and option on the any options roasted when I and state can that an don't subjective of has his take on and in from royal everything took raising our have behind success you the mechanic.",
      },
      {
        para2: "And, higher by agency; In from their in and we spirit, through merely and doctor's small him sounded a all now, with that put gift white highly geared that was left back as of or logged important. A over have the large try understanding the believe. Perfected been viewer. Shreds early willingly safely what passion the.",
      },
      {
        para3: "In an ideal world this website wouldn’t exist, a client would acknowledge the importance of having web copy before the design starts. Needless to say it’s very important, content is king and people are beginning to understand that. However, back over in reality some project schedules and budgets don’t allow for web copy to be written before the design phase, this is sad but true.",
      },
    ],
  },
  {
    id: 4,
    cover: "../images/hero/hero4.jpg",
    title: "Why the biggest, fattest Indian wedding aka the Ambani extravaganza was also a humbling experience",
    authorName: "mona lisa",
    authorImg: "../images/author.jpg",
    time: "08 jul - 2024",
    desc: [
      {
        para1: "You audience. Least, the recently his repeat the this avarice for the have and was on would before the concise bedding were hall politely name be regretting have of even five of it the his are there again. Word seven designer far lady problem will have work with you to fully understand your business to achieve.",
      },
      {
        para2: "We work with clients big and small across a range of sectors and we utilize all forms of media to get your name out there in a way that’s right for you. We believe that analysis of your company and your customers is key in responding effectively to your promotional needs and we will work with you.",
      },
      {
        para3: "We have a number of different teams within our agency that specialise in different areas of business so you can be sure that you won’t receive a generic service and although we can’t boast years and years of service we can ensure you that is a good thing in this industry.",
      },
    ],
    details: [
      {
        title: "Starting a new company is easy",
      },
      { para1: "Our teams are up to date with the latest technologies, media trends and are keen to prove themselves in this industry and that’s what you want from an advertising agency, not someone who is relying on the same way of doing things that worked 10 years, 5 years or even a year ago." },
      {
        quote: "Scarfs, still not this no with explains it me and option on the any options roasted when I and state can that an don't subjective of has his take on and in from royal everything took raising our have behind success you the mechanic.",
      },
      {
        para2: "And, higher by agency; In from their in and we spirit, through merely and doctor's small him sounded a all now, with that put gift white highly geared that was left back as of or logged important. A over have the large try understanding the believe. Perfected been viewer. Shreds early willingly safely what passion the.",
      },
      {
        para3: "In an ideal world this website wouldn’t exist, a client would acknowledge the importance of having web copy before the design starts. Needless to say it’s very important, content is king and people are beginning to understand that. However, back over in reality some project schedules and budgets don’t allow for web copy to be written before the design phase, this is sad but true.",
      },
    ],
  },
]
export const newsData = [
  {
    id: 1,
    category: "India",
    title: "Discovering India's Rich Cultural Heritage",
    date: "19. February 2022",
    comments: 0,
    cover: "../images/popular/pop1.jpg",
    desc: "Explore the vibrant traditions and customs of India.",
  },
  {
    id: 2,
    category: "India",
    title: "The Rise of Startups in India",
    date: "20. March 2022",
    comments: 2,
    cover: "../images/popular/pop2.jpg",
    desc: "An in-depth look at the startup ecosystem in India.",
  },
  {
    id: 3,
    category: "India",
    title: "India's Space Missions: A Journey to the Stars",
    date: "15. April 2022",
    comments: 5,
    cover: "../images/popular/pop3.jpg",
    desc: "The achievements of ISRO and its future plans.",
  },
  {
    id: 4,
    category: "India",
    title: "Traditional Indian Cuisine: A Culinary Adventure",
    date: "10. May 2022",
    comments: 1,
    cover: "../images/popular/pop4.jpg",
    desc: "Dive into the diverse and delicious world of Indian food.",
  },
  {
    id: 5,
    category: "India",
    title: "Historic Monuments of India: A Timeless Legacy",
    date: "25. June 2022",
    comments: 3,
    cover: "../images/popular/pop5.jpg",
    desc: "Exploring the architectural wonders of India.",
  },
  {
    id: 6,
    category: "India",
    title: "The Vibrant Festivals of India",
    date: "30. July 2022",
    comments: 4,
    cover: "../images/popular/pop6.jpg",
    desc: "Celebrating the colorful festivals across the nation.",
  },
  {
    id: 7,
    category: "India",
    title: "Bollywood: The Heartbeat of Indian Cinema",
    date: "5. August 2022",
    comments: 6,
    cover: "../images/popular/pop7.jpg",
    desc: "A look into the world of Indian cinema.",
  },
  {
    id: 8,
    category: "India",
    title: "Yoga and Wellness: India's Gift to the World",
    date: "10. September 2022",
    comments: 0,
    cover: "../images/popular/pop8.jpg",
    desc: "Understanding the ancient practice of yoga.",
  },
  {
    id: 9,
    category: "India",
    title: "The Growth of E-commerce in India",
    date: "15. October 2022",
    comments: 2,
    cover: "../images/popular/pop9.jpg",
    desc: "The rise of online shopping in India.",
  },
  {
    id: 10,
    category: "India",
    title: "Exploring India's National Parks",
    date: "20. November 2022",
    comments: 1,
    cover: "../images/popular/pop10.jpg",
    desc: "A guide to the wildlife sanctuaries in India.",
  },
  {
    id: 11,
    category: "India",
    title: "The Evolution of Indian Fashion",
    date: "25. December 2022",
    comments: 5,
    cover: "../images/popular/pop11.jpg",
    desc: "Tracing the history of fashion in India.",
  },
  {
    id: 12,
    category: "India",
    title: "India's Technological Advancements",
    date: "1. January 2023",
    comments: 4,
    cover: "../images/popular/pop12.jpg",
    desc: "India's contributions to the tech world.",
  },
  {
    id: 13,
    category: "International",
    title: "Global Trade and Its Impact on Economies",
    date: "19. February 2022",
    comments: 0,
    cover: "../images/popular/pop1.jpg",
    desc: "The influence of global trade on world economies.",
  },
  {
    id: 14,
    category: "International",
    title: "Climate Change: A Global Challenge",
    date: "20. March 2022",
    comments: 2,
    cover: "../images/popular/pop2.jpg",
    desc: "Addressing the urgent issue of climate change.",
  },
  {
    id: 15,
    category: "International",
    title: "Innovations in Renewable Energy",
    date: "15. April 2022",
    comments: 5,
    cover: "../images/popular/pop3.jpg",
    desc: "The latest developments in renewable energy sources.",
  },
  {
    id: 16,
    category: "International",
    title: "Advancements in Healthcare Technology",
    date: "10. May 2022",
    comments: 1,
    cover: "../images/popular/pop4.jpg",
    desc: "How technology is transforming healthcare.",
  },
  {
    id: 17,
    category: "International",
    title: "Exploring the Wonders of Space",
    date: "25. June 2022",
    comments: 3,
    cover: "../images/popular/pop5.jpg",
    desc: "The latest discoveries in space exploration.",
  },
  {
    id: 18,
    category: "International",
    title: "Cultural Diversity Around the World",
    date: "30. July 2022",
    comments: 4,
    cover: "../images/popular/pop6.jpg",
    desc: "Celebrating cultural diversity across the globe.",
  },
  {
    id: 19,
    category: "International",
    title: "The Future of Artificial Intelligence",
    date: "5. August 2022",
    comments: 6,
    cover: "../images/popular/pop7.jpg",
    desc: "Exploring the potential of AI in various fields.",
  },
  {
    id: 20,
    category: "International",
    title: "Global Health Initiatives and Their Impact",
    date: "10. September 2022",
    comments: 0,
    cover: "../images/popular/pop8.jpg",
    desc: "The importance of global health initiatives.",
  },
  {
    id: 21,
    category: "International",
    title: "Economic Policies and Their Global Effects",
    date: "15. October 2022",
    comments: 2,
    cover: "../images/popular/pop9.jpg",
    desc: "Analyzing the impact of economic policies worldwide.",
  },
  {
    id: 22,
    category: "International",
    title: "The Rise of Digital Currency",
    date: "20. November 2022",
    comments: 1,
    cover: "../images/popular/pop10.jpg",
    desc: "Understanding the growth of digital currencies.",
  },
  {
    id: 23,
    category: "International",
    title: "Innovative Solutions for Urban Development",
    date: "25. December 2022",
    comments: 5,
    cover: "../images/popular/pop11.jpg",
    desc: "Sustainable solutions for urban development.",
  },
  {
    id: 24,
    category: "International",
    title: "The Role of Technology in Education",
    date: "1. January 2023",
    comments: 4,
    cover: "../images/popular/pop12.jpg",
    desc: "How technology is shaping the future of education.",
  },
  {
    id: 25,
    category: "Sports",
    title: "The Evolution of Modern Sports",
    date: "19. February 2022",
    comments: 0,
    cover: "../images/popular/pop1.jpg",
    desc: "A look at the history and evolution of modern sports.",
  },
  {
    id: 26,
    category: "Sports",
    title: "Training Techniques of Elite Athletes",
    date: "20. March 2022",
    comments: 2,
    cover: "../images/popular/pop2.jpg",
    desc: "Training methods used by top athletes.",
  },
  {
    id: 27,
    category: "Sports",
    title: "The Impact of Sports on Society",
    date: "15. April 2022",
    comments: 5,
    cover: "../images/popular/pop3.jpg",
    desc: "The social and cultural impact of sports.",
  },
  {
    id: 28,
    category: "Sports",
    title: "Breakthroughs in Sports Medicine",
    date: "10. May 2022",
    comments: 1,
    cover: "../images/popular/pop4.jpg",
    desc: "Advancements in sports injury prevention and treatment.",
  },
  {
    id: 29,
    category: "Sports",
    title: "The Rise of E-Sports",
    date: "25. June 2022",
    comments: 3,
    cover: "../images/popular/pop5.jpg",
    desc: "The growing popularity of competitive gaming.",
  },
  {
    id: 30,
    category: "Sports",
    title: "Iconic Moments in Sports History",
    date: "30. July 2022",
    comments: 4,
    cover: "../images/popular/pop6.jpg",
    desc: "Memorable moments that defined sports history.",
  },
  {
    id: 31,
    category: "Sports",
    title: "Women in Sports: Breaking Barriers",
    date: "5. August 2022",
    comments: 6,
    cover: "../images/popular/pop7.jpg",
    desc: "Celebrating the achievements of women in sports.",
  },
  {
    id: 32,
    category: "Sports",
    title: "The Role of Technology in Sports",
    date: "10. September 2022",
    comments: 0,
    cover: "../images/popular/pop8.jpg",
    desc: "How technology is changing the sports industry.",
  },
  {
    id: 33,
    category: "Sports",
    title: "Sports Psychology: Mental Game of Champions",
    date: "15. October 2022",
    comments: 2,
    cover: "../images/popular/pop9.jpg",
    desc: "The importance of mental toughness in sports.",
  },
  {
    id: 34,
    category: "Sports",
    title: "The Economics of Professional Sports",
    date: "20. November 2022",
    comments: 1,
    cover: "../images/popular/pop10.jpg",
    desc: "Financial aspects of the professional sports industry.",
  },
  {
    id: 35,
    category: "Sports",
    title: "Doping in Sports: Challenges and Solutions",
    date: "25. December 2022",
    comments: 5,
    cover: "../images/popular/pop11.jpg",
    desc: "Addressing the issue of doping in sports.",
  },
  {
    id: 36,
    category: "Sports",
    title: "The Future of Sports Broadcasting",
    date: "1. January 2023",
    comments: 4,
    cover: "../images/popular/pop12.jpg",
    desc: "Trends and innovations in sports broadcasting.",
  },
  {
    id: 37,
    category: "Social Media",
    title: "The Rise of Influencer Marketing",
    date: "19. February 2022",
    comments: 0,
    cover: "../images/popular/pop1.jpg",
    desc: "How influencers are shaping marketing strategies.",
  },
  {
    id: 38,
    category: "Social Media",
    title: "Social Media's Impact on Mental Health",
    date: "20. March 2022",
    comments: 2,
    cover: "../images/popular/pop2.jpg",
    desc: "The effects of social media on mental well-being.",
  },
  {
    id: 39,
    category: "Social Media",
    title: "The Evolution of Social Media Platforms",
    date: "15. April 2022",
    comments: 5,
    cover: "../images/popular/pop3.jpg",
    desc: "How social media platforms have evolved over the years.",
  },
  {
    id: 40,
    category: "Social Media",
    title: "Privacy Concerns in the Age of Social Media",
    date: "10. May 2022",
    comments: 1,
    cover: "../images/popular/pop4.jpg",
    desc: "Addressing privacy issues on social media.",
  },
  {
    id: 41,
    category: "Social Media",
    title: "The Power of Viral Content",
    date: "25. June 2022",
    comments: 3,
    cover: "../images/popular/pop5.jpg",
    desc: "Understanding what makes content go viral.",
  },
  {
    id: 42,
    category: "Social Media",
    title: "Social Media Trends to Watch in 2023",
    date: "30. July 2022",
    comments: 4,
    cover: "../images/popular/pop6.jpg",
    desc: "Predictions for upcoming social media trends.",
  },
  {
    id: 43,
    category: "Social Media",
    title: "The Role of Social Media in Politics",
    date: "5. August 2022",
    comments: 6,
    cover: "../images/popular/pop7.jpg",
    desc: "How social media is influencing political landscapes.",
  },
  {
    id: 44,
    category: "Social Media",
    title: "Building a Personal Brand on Social Media",
    date: "10. September 2022",
    comments: 0,
    cover: "../images/popular/pop8.jpg",
    desc: "Tips for creating and maintaining a personal brand.",
  },
  {
    id: 45,
    category: "Social Media",
    title: "The Economics of Social Media",
    date: "15. October 2022",
    comments: 2,
    cover: "../images/popular/pop9.jpg",
    desc: "Monetization strategies for social media platforms.",
  },
  {
    id: 46,
    category: "Social Media",
    title: "Social Media and Cultural Exchange",
    date: "20. November 2022",
    comments: 1,
    cover: "../images/popular/pop10.jpg",
    desc: "How social media fosters cultural exchange.",
  },
  {
    id: 47,
    category: "Social Media",
    title: "Combating Misinformation on Social Media",
    date: "25. December 2022",
    comments: 5,
    cover: "../images/popular/pop11.jpg",
    desc: "Efforts to fight misinformation and fake news.",
  },
  {
    id: 48,
    category: "Social Media",
    title: "The Future of Social Media Advertising",
    date: "1. January 2023",
    comments: 4,
    cover: "../images/popular/pop12.jpg",
    desc: "Trends in social media advertising.",
  },
  {
    id: 49,
    category: "Science",
    title: "Breakthroughs in Genetic Research",
    date: "19. February 2022",
    comments: 0,
    cover: "../images/popular/pop1.jpg",
    desc: "The latest advancements in genetic research.",
  },
  {
    id: 50,
    category: "Science",
    title: "Exploring the Depths of the Ocean",
    date: "20. March 2022",
    comments: 2,
    cover: "../images/popular/pop2.jpg",
    desc: "Discoveries in oceanography and marine biology.",
  },
  {
    id: 51,
    category: "Science",
    title: "The Mysteries of Quantum Physics",
    date: "15. April 2022",
    comments: 5,
    cover: "../images/popular/pop3.jpg",
    desc: "Understanding the complex world of quantum physics.",
  },
  {
    id: 52,
    category: "Science",
    title: "Advances in Medical Technology",
    date: "10. May 2022",
    comments: 1,
    cover: "../images/popular/pop4.jpg",
    desc: "The latest developments in medical technology.",
  },
  {
    id: 53,
    category: "Science",
    title: "Climate Science: Understanding Our Planet",
    date: "25. June 2022",
    comments: 3,
    cover: "../images/popular/pop5.jpg",
    desc: "Research and insights into climate science.",
  },
  {
    id: 54,
    category: "Science",
    title: "The Search for Extraterrestrial Life",
    date: "30. July 2022",
    comments: 4,
    cover: "../images/popular/pop6.jpg",
    desc: "Efforts to find life beyond Earth.",
  },
  {
    id: 55,
    category: "Science",
    title: "The Human Brain: Unlocking Its Secrets",
    date: "5. August 2022",
    comments: 6,
    cover: "../images/popular/pop7.jpg",
    desc: "Research into the functions and mysteries of the brain.",
  },
  {
    id: 56,
    category: "Science",
    title: "Sustainable Energy Solutions",
    date: "10. September 2022",
    comments: 0,
    cover: "../images/popular/pop8.jpg",
    desc: "Innovations in sustainable energy.",
  },
  {
    id: 57,
    category: "Science",
    title: "Nanotechnology: The Future of Science",
    date: "15. October 2022",
    comments: 2,
    cover: "../images/popular/pop9.jpg",
    desc: "Exploring the potential of nanotechnology.",
  },
  {
    id: 58,
    category: "Science",
    title: "Robotics and Automation",
    date: "20. November 2022",
    comments: 1,
    cover: "../images/popular/pop10.jpg",
    desc: "The rise of robotics and automation.",
  },
  {
    id: 59,
    category: "Science",
    title: "The Science of Sleep",
    date: "25. December 2022",
    comments: 5,
    cover: "../images/popular/pop11.jpg",
    desc: "Understanding the science behind sleep.",
  },
  {
    id: 60,
    category: "Science",
    title: "Exploring the Solar System",
    date: "1. January 2023",
    comments: 4,
    cover: "../images/popular/pop12.jpg",
    desc: "Missions and discoveries in our solar",
  },
    {
      id: 61,
      category: "Science",
      title: "The Science of Sleep",
      date: "25. December 2022",
      comments: 5,
      cover: "../images/popular/pop11.jpg",
      desc: "Understanding the science behind sleep.",
    },
    {
      id: 62,
      category: "Science",
      title: "Exploring the Solar System",
      date: "1. January 2023",
      comments: 4,
      cover: "../images/popular/pop12.jpg",
      desc: "Missions and discoveries in our solar system.",
    },
    {
      id: 63,
      category: "Technology",
      title: "The Evolution of Smartphones",
      date: "19. February 2022",
      comments: 0,
      cover: "../images/popular/pop1.jpg",
      desc: "How smartphones have evolved over the years.",
    },
    {
      id: 64,
      category: "Technology",
      title: "The Future of Quantum Computing",
      date: "20. March 2022",
      comments: 2,
      cover: "../images/popular/pop2.jpg",
      desc: "Exploring the potential of quantum computers.",
    },
    {
      id: 65,
      category: "Technology",
      title: "Artificial Intelligence in Everyday Life",
      date: "15. April 2022",
      comments: 5,
      cover: "../images/popular/pop3.jpg",
      desc: "How AI is integrated into our daily routines.",
    },
    {
      id: 66,
      category: "Technology",
      title: "Cybersecurity: Protecting Your Digital World",
      date: "10. May 2022",
      comments: 1,
      cover: "../images/popular/pop4.jpg",
      desc: "Tips and strategies for maintaining digital security.",
    },
    {
      id: 67,
      category: "Technology",
      title: "The Rise of Augmented Reality",
      date: "25. June 2022",
      comments: 3,
      cover: "../images/popular/pop5.jpg",
      desc: "Innovations and applications of augmented reality.",
    },
    {
      id: 68,
      category: "Technology",
      title: "5G Technology: What You Need to Know",
      date: "30. July 2022",
      comments: 4,
      cover: "../images/popular/pop6.jpg",
      desc: "Understanding the impact of 5G technology.",
    },
    {
      id: 69,
      category: "Technology",
      title: "The Internet of Things: Connecting Everything",
      date: "5. August 2022",
      comments: 6,
      cover: "../images/popular/pop7.jpg",
      desc: "How IoT is changing the way we interact with the world.",
    },
    {
      id: 70,
      category: "Technology",
      title: "Blockchain Technology: Beyond Cryptocurrency",
      date: "10. September 2022",
      comments: 0,
      cover: "../images/popular/pop8.jpg",
      desc: "Exploring the uses of blockchain beyond digital currencies.",
    },
    {
      id: 71,
      category: "Technology",
      title: "The Role of Technology in Remote Work",
      date: "15. October 2022",
      comments: 2,
      cover: "../images/popular/pop9.jpg",
      desc: "How technology is facilitating remote work.",
    },
    {
      id: 72,
      category: "Technology",
      title: "Emerging Trends in Tech Startups",
      date: "20. November 2022",
      comments: 1,
      cover: "../images/popular/pop10.jpg",
      desc: "Innovative trends in the tech startup world.",
    },
    {
      id: 73,
      category: "Technology",
      title: "The Impact of Technology on Education",
      date: "25. December 2022",
      comments: 5,
      cover: "../images/popular/pop11.jpg",
      desc: "How technology is transforming the educational landscape.",
    },
    {
      id: 74,
      category: "Technology",
      title: "Future Technologies: What’s Next?",
      date: "1. January 2023",
      comments: 4,
      cover: "../images/popular/pop12.jpg",
      desc: "A look at upcoming technological innovations.",
    },
    {
      id: 75,
      category: "Business",
      title: "The Rise of E-commerce",
      date: "19. February 2022",
      comments: 0,
      cover: "../images/popular/pop1.jpg",
      desc: "How e-commerce is reshaping the retail landscape.",
    },
    {
      id: 76,
      category: "Business",
      title: "Entrepreneurship in the Digital Age",
      date: "20. March 2022",
      comments: 2,
      cover: "../images/popular/pop2.jpg",
      desc: "Starting and managing a business in the digital era.",
    },
    {
      id: 77,
      category: "Business",
      title: "Investment Strategies for 2023",
      date: "15. April 2022",
      comments: 5,
      cover: "../images/popular/pop3.jpg",
      desc: "Effective investment strategies for the coming year.",
    },
    {
      id: 78,
      category: "Business",
      title: "Understanding Market Trends",
      date: "10. May 2022",
      comments: 1,
      cover: "../images/popular/pop4.jpg",
      desc: "How to analyze and interpret market trends.",
    },
    {
      id: 79,
      category: "Business",
      title: "The Impact of Globalization on Business",
      date: "25. June 2022",
      comments: 3,
      cover: "../images/popular/pop5.jpg",
      desc: "How globalization is affecting businesses worldwide.",
    },
    {
      id: 80,
      category: "Business",
      title: "Innovative Business Models",
      date: "30. July 2022",
      comments: 4,
      cover: "../images/popular/pop6.jpg",
      desc: "Exploring new and innovative business models.",
    },
    {
      id: 81,
      category: "Business",
      title: "The Role of Technology in Business Growth",
      date: "5. August 2022",
      comments: 6,
      cover: "../images/popular/pop7.jpg",
      desc: "How technology drives business expansion.",
    },
    {
      id: 82,
      category: "Business",
      title: "Sustainable Business Practices",
      date: "10. September 2022",
      comments: 0,
      cover: "../images/popular/pop8.jpg",
      desc: "Adopting sustainable practices in business.",
    },
    {
      id: 83,
      category: "Business",
      title: "Navigating Financial Challenges",
      date: "15. October 2022",
      comments: 2,
      cover: "../images/popular/pop9.jpg",
      desc: "Strategies for overcoming financial hurdles.",
    },
    {
      id: 84,
      category: "Business",
      title: "The Future of Work: Trends and Predictions",
      date: "20. November 2022",
      comments: 1,
      cover: "../images/popular/pop10.jpg",
      desc: "What to expect in the future of the workforce.",
    },
    {
      id: 85,
      category: "Business",
      title: "The Importance of Networking",
      date: "25. December 2022",
      comments: 5,
      cover: "../images/popular/pop11.jpg",
      desc: "Building and maintaining professional networks.",
    },
    {
      id: 86,
      category: "Business",
      title: "Understanding Consumer Behavior",
      date: "1. January 2023",
      comments: 4,
      cover: "../images/popular/pop12.jpg",
      desc: "Insights into consumer purchasing patterns.",
    },
    {
      id: 87,
      category: "Electric Cars",
      title: "The Future of Electric Vehicles",
      date: "19. February 2022",
      comments: 0,
      cover: "../images/popular/pop1.jpg",
      desc: "How electric vehicles are shaping the future of transportation.",
    },
    {
      id: 88,
      category: "Electric Cars",
      title: "Charging Infrastructure: What's Needed?",
      date: "20. March 2022",
      comments: 2,
      cover: "../images/popular/pop2.jpg",
      desc: "Developing charging infrastructure for electric cars.",
    },
    {
      id: 89,
      category: "Electric Cars",
      title: "Top Electric Cars of 2023",
      date: "15. April 2022",
      comments: 5,
      cover: "../images/popular/pop3.jpg",
      desc: "A review of the best electric cars available this year.",
    },
    {
      id: 90,
      category: "Electric Cars",
      title: "The Benefits of Electric Vehicles",
      date: "10. May 2022",
      comments: 1,
      cover: "../images/popular/pop4.jpg",
      desc: "Advantages of switching to electric vehicles.",
    },
    {
      id: 91,
      category: "Electric Cars",
      title: "Challenges in Electric Car Adoption",
      date: "25. June 2022",
      comments: 3,
      cover: "../images/popular/pop5.jpg",
      desc: "Barriers to the widespread adoption of electric cars.",
    },
    {
      id: 92,
      category: "Electric Cars",
      title: "Electric Cars vs. Traditional Cars",
      date: "30. July 2022",
      comments: 4,
      cover: "../images/popular/pop6.jpg",
      desc: "Comparing electric vehicles with traditional internal combustion engine cars.",
    },
    {
      id: 93,
      category: "Electric Cars",
      title: "Innovations in Electric Car Technology",
      date: "5. August 2022",
      comments: 6,
      cover: "../images/popular/pop7.jpg",
      desc: "New technological advancements in electric cars.",
    },
    {
      id: 94,
      category: "Electric Cars",
      title: "The Environmental Impact of Electric Cars",
      date: "10. September 2022",
      comments: 0,
      cover: "../images/popular/pop8.jpg",
      desc: "How electric cars affect the environment.",
    },
    {
      id: 95,
      category: "Electric Cars",
      title: "Electric Car Battery Technology",
      date: "15. October 2024",
      comments: 2,
      cover: "../images/popular/pop9.jpg",
      desc: "Understanding the technology behind electric car batteries.",
    },
    {
      id: 96,
      category: "Electric Cars",
      title: "The Future of Autonomous Electric Vehicles",
      date: "20. November 2017",
      comments: 1,
      cover: "../images/popular/pop10.jpg",
      desc: "Exploring the potential of self-driving electric cars.",
    }
  ];
  


